language: chs
version: '2021-12-10'
worlds-disabled: world1, world2
允许附魔: true
NeedFailedTips: |-
  §c=== 需求未满足 ===
  缺少：§7%1
品阶:
- §5一阶装备
- §5二阶装备
- §5三阶装备
- §5四阶装备
- §5五阶装备
- §3六阶装备
- §9七阶装备
- §c幻域元素
- §6§l传说中的魔剑
- §5§l人工产物
- §3[§e觉醒§3]§b✪§f✪✪✪✪
- §3[§e觉醒§3]§b✪✪§f✪✪✪
- §3[§e觉醒§3]§b✪✪✪§f✪✪
- §3[§e觉醒§3]§b✪✪✪✪§f✪
- §3[§e觉醒§3]§b✪✪✪✪✪
- §6神圣能量 §7✧✧✧
- §6神圣能量 §✦§7✧✧
- §6神圣能量 §d✦✦§7✧
- §6神圣能量 §d✦✦✦
- §6神圣能量 §d✦✦✦✦✦✦✦✦✦✦
- §7其它
- §9§l传奇之物
稀有度:
- §b普通
- §a优秀
- §9稀有
- §5史诗
- §6传说
- §5§l远古史诗
- §6§l远古传说
- §c奇迹
- §c§l古代奇迹
- §e神化武装
- §4§l最终圣具
- §l§d亚神器
- §l§3认知之巅
- §e定制
分解所得:
- 村正:
  - mi give "{player}" 村正之魂 1
- - |-
    mi give "{player}" 下级装备核心 1
    mi give "{player}" 一阶锻造材料 1
  - |-
    mi give "{player}" 下级装备核心 1
    mi give "{player}" 一阶锻造材料 3
    mi give "{player}" 二阶锻造材料 1
  - |-
    mi give "{player}" 下级装备核心 1
    mi give "{player}" 三阶锻造材料 1
    mi give "{player}" 二阶锻造材料 3
  - |-
    mi give "{player}" 中级装备核心 1
    mi give "{player}" 四阶锻造材料 1
    mi give "{player}" 三阶锻造材料 3
  - |-
    mi give "{player}" 中级装备核心 1
    mi give "{player}" 五阶锻造材料 1
    mi give "{player}" 四阶锻造材料 3
锻造模式: 1.0
锻造词条: true
锻造:
- - §3真理
  - §4逆天
  - §6传说
  - §5史诗
  - §9稀有
  - §b精良
  - §a优良
  - §7普通
  - §1粗糙
- - 0.005
  - 0.025
  - 0.03
  - 0.05
  - 0.14
  - 0.175
  - 0.2
  - 0.275
  - 0.1
- - 3-2.75
  - 2.75-2.45
  - 2.45-2
  - 2-1.65
  - 1.65-1.4
  - 1.4-1.15
  - 1.15-1
  - 1-0.9
  - 0.9-0.8
锻造等级:
  经验公式: 57*({等级}*{等级})
  等级公式: Math.sqrt({经验}/57)
  最大等级: 10.0
默认镶嵌概率: 0.35
ForingExp:
  onlySameLevel: false
  nonSameLevelGive: 0.1
AttrDisplayPercent:
- 暴击倍率
- 吸血倍率
- 护甲强度
- 反伤倍率
- 经验加成
- 暴击率
- 吸血率
- 破防率
- 反伤率
- 闪避率
- 暴击抵抗
- 吸血抵抗
- 命中率
- 伤害加成
- 攻击加成
- 防御加成
- 生命加成
useHarmFloatWord: true
itemDefaultBind: true
defaultAttr:
  血量值: 20.0
  破防率: 1.0
Seiko:
  enable: false
  need:
  - money@100000.0
  - money@100000.0
  - money@100000.0
  - money@1000000.0
  - money@1000000.0
  - money@1000000.0
  - money@1.0E7
  - money@1.0E7
  - money@1.0E7
  - money@1.0E8
  - money@1.0E8
  - money@1.0E8
  failedAddition: 0.05
  chance:
  - 1.0
  - 0.8
  - 0.75
  - 0.7
  - 0.65
  - 0.6
  - 0.55
  - 0.5
  - 0.45
  - 0.4
  - 0.35
  - 0.3
  - 0.25
  - 0.2
  - 0.15
  - 0.1
  failed:
  - - 4.0
    - 0.0
  - - 10.0
    - 0.5
    - 0.5
  - - 16.0
    - 0.8
    - 0.2
  broadcastMessage:
  - 6.0
  - §c§l[精工系统] §r§a%p §f欧皇附体！成功打造出§e %lv §f级 %weapon §r！！
  attr:
  - - 破防攻击: 1000.0
    - 破防攻击: 2000.0
    - 破防攻击: 3000.0
    - 破防攻击: 4000.0
    - 破防攻击: 5000.0
    - 破防攻击: 6000.0
    - 破防攻击: 7000.0
    - 破防攻击: 8000.0
    - 破防攻击: 9000.0
    - 破防攻击: 10000.0
  - - 防御力: 500.0
    - 防御力: 1000.0
    - 防御力: 1500.0
    - 防御力: 2000.0
    - 防御力: 2500.0
    - 防御力: 3000.0
    - 防御力: 3500.0
    - 防御力: 4000.0
    - 防御力: 4500.0
    - 防御力: 5000.0
GradeSymbol:
  enable: true
  list:
  - - 9.0
    - 6.0
    - 3.0
    - 1.0
  - - ❂
    - ✹
    - ✸
    - ✶
unbind:
  enable: true
  onlyOp: true
  failExec: []
  succExec:
  - uie exec 解除灵魂绑定 "%p" true
bind:
  enable: true
  defaultBind: true
Strengthen:
  enable: true
  model: 2.0
  failedAddition: 0.005
  need:
  - mi@10:淬炼用魔矿||money@100000
  - mi@30:淬炼用魔矿||money@100000
  - mi@60:淬炼用魔矿||money@100000
  - mi@90:淬炼用魔矿||money@100000
  - mi@120:淬炼用魔矿||money@100000
  - mi@150:淬炼用魔矿||money@100000
  - mi@180:淬炼用魔矿||money@100000
  - mi@210:淬炼用魔矿||money@100000
  - mi@230:淬炼用魔矿||money@100000
  - mi@260:淬炼用魔矿||money@100000
  - mi@290:淬炼用魔矿||money@100000
  - mi@320:淬炼用魔矿||money@100000
  - mi@350:淬炼用魔矿||money@100000
  - mi@380:淬炼用魔矿||money@100000
  - mi@410:淬炼用魔矿||money@100000
  chance:
  - 1.0
  - 0.8
  - 0.75
  - 0.7
  - 0.65
  - 0.6
  - 0.55
  - 0.5
  - 0.45
  - 0.4
  - 0.35
  - 0.3
  - 0.25
  - 0.2
  - 0.15
  - 0.1
  failed:
  - - 4.0
    - 0.0
  - - 10.0
    - 0.5
    - 0.5
  - - 16.0
    - 0.8
    - 0.2
  broadcastMessage:
  - 6.0
  - §c§l[淬炼系统] §r§a%p §f欧皇附体！成功打造出§e %lv §f级 %weapon §r！！
  attr:
  - - 攻击加成: 0.01
      暴击倍率: 0.01
    - 攻击加成: 0.04
      暴击倍率: 0.04
    - 攻击加成: 0.09
      暴击倍率: 0.09
    - 攻击加成: 0.16
      暴击倍率: 0.16
    - 攻击加成: 0.25
      暴击倍率: 0.25
    - 攻击加成: 0.36
      暴击倍率: 0.36
      吸血倍率: 0.05
    - 攻击加成: 0.49
      暴击倍率: 0.49
      吸血倍率: 0.1
    - 攻击加成: 0.64
      暴击倍率: 0.64
      吸血倍率: 0.15
    - 攻击加成: 0.81
      暴击倍率: 0.81
      吸血倍率: 0.2
    - 攻击加成: 1.0
      暴击倍率: 1.0
      吸血倍率: 0.25
    - 攻击加成: 1.21
      暴击倍率: 1.21
      吸血倍率: 0.3
      暴击率: 0.01
    - 攻击加成: 1.44
      暴击倍率: 1.44
      吸血倍率: 0.35
      暴击率: 0.02
    - 攻击加成: 1.69
      暴击倍率: 1.69
      吸血倍率: 0.4
      暴击率: 0.03
    - 攻击加成: 1.96
      暴击倍率: 1.96
      吸血倍率: 0.45
      暴击率: 0.04
    - 攻击加成: 2.25
      暴击倍率: 0.15
      吸血倍率: 0.5
      暴击率: 0.05
  - - 生命加成: 0.01
      防御加成: 0.01
    - 生命加成: 0.04
      防御加成: 0.04
    - 生命加成: 0.09
      防御加成: 0.09
    - 生命加成: 0.16
      防御加成: 0.16
    - 生命加成: 0.25
      防御加成: 0.25
    - 生命加成: 0.36
      防御加成: 0.36
    - 生命加成: 0.49
      防御加成: 0.49
    - 生命加成: 0.64
      防御加成: 0.64
    - 生命加成: 0.81
      防御加成: 0.81
    - 生命加成: 1.0
      防御加成: 1.0
    - 生命加成: 1.21
      防御加成: 1.21
      闪避: 0.05
    - 生命加成: 1.44
      防御加成: 1.44
      闪避: 0.075
    - 生命加成: 1.69
      防御加成: 1.69
      闪避: 0.1
    - 生命加成: 1.96
      防御加成: 1.96
      闪避: 0.125
    - 生命加成: 2.25
      防御加成: 2.25
      闪避: 0.15
  style:
    icon: ●
    firstList:
    - §f§l
    - §f§l
    - §a§l
    - §a§l
    - §b§l
    - §b§l
    - §9§l
    - §9§l
    - §5§l
    - §5§l
    - §6§l
    - §6§l
    - §d§l
    - §d§l
    - §3§l
defaultCritMultiply: 1.0
EffectSuit:
  新手套装:2:
    attr:
      血量值: 50.0
稀有度品阶排序: false
Rune:
  enable: true
