name: NWeapon CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: |
        npm install
    - name: TypeScript Comp
      run: |
        tsc > /dev/null || true
    - name: Build
      run: |
        pwd
        node ./scripts/move.js
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "@NWeaponRe"
        path: /home/runner/work/NWeaponRe/NWeaponRe/dist/@NWeaponRe/
